### ISSUE TITLE
SubcomposeLayout or similar to render large amounts of markers or polyline

### ISSUE THREAD

**Issue by AagitoEx** [googlemaps/android-maps-compose#234]
Is it possible to use **key** based composition just like SubcomposeLayout (LazyColumn) to add large amounts of markers and polygons?

This will fulfill the case where a list of markers changes frequently but have stable ids.

**Comment by DSteve595** [comment]
Since you have stable keys for the markers, you can use the `key` composable to leverage them for better performance. This won't achieve lazy behavior like `LazyColumn`, but marker objects are quite light, and it's likely not necessary. If you have a repro case where performance is negatively impacted by having lots of markers with `key`s, we can definitely explore it then.
